In [1]:
#Backpropogation Algorithm

In [2]:
import numpy as np

In [3]:
input_layer_neurons=2
hidden_layer_neurons=3
output_neurons=1
print("Number of input layer neurons: ",input_layer_neurons)
print("Number of hidden layer neurons: ",hidden_layer_neurons)
print("Number of output layer neurons: ",output_neurons)

Number of input layer neurons:  2
Number of hidden layer neurons:  3
Number of output layer neurons:  1


In [4]:
wh=np.random.uniform(size=(input_layer_neurons,hidden_layer_neurons))
print("Weights from input layer to hidden layer : \n",wh)
bh=np.random.uniform(size=(1,hidden_layer_neurons))
print("Bias between input and hidden layers : \n",bh)
wout=np.random.uniform(size=(hidden_layer_neurons,output_neurons))
print("Weights from hidden layer to output layer : \n",wout)
bout=np.random.uniform(size=(1,output_neurons))
print("Bias between output and hidden layers : \n",bout)

Weights from input layer to hidden layer : 
 [[0.43592256 0.14431515 0.11629298]
 [0.46229401 0.33778041 0.06183164]]
Bias between input and hidden layers : 
 [[0.95123825 0.59329321 0.06498914]]
Weights from hidden layer to output layer : 
 [[0.39934639]
 [0.15650915]
 [0.46135234]]
Bias between output and hidden layers : 
 [[0.56438216]]


In [5]:
epoch=7000
lr=0.1
x=np.array(([2,9],[1,5],[3,6]))
y=np.array(([92],[86],[89]))
x=x/np.amax(x,axis=0)
x

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
def derivatives_sigmoid(x):
    return x*(1-x)

In [9]:
for i in range(epoch):
    hinp1=np.dot(x,wh)
    hinp=hinp1+bh
    hlayer_act=sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    EO=y-output
    outgrad=derivatives_sigmoid(output)
    d_output=EO*outgrad
    EH=d_output.dot(wout.T)
    hiddengrad=derivatives_sigmoid(hlayer_act)
    d_hiddenlayer=EH*hiddengrad
    wout+=hlayer_act.T.dot(d_output)*lr
    wht=x.T.dot(d_hiddenlayer)*lr
    print("Input : \n",str(x))
    print("Actual o/p : \n",str(y))
    print("Predicted o/p : \n",output)

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99973897]
 [0.99961017]
 [0.99972963]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99974216]
 [0.99961469]
 [0.99973292]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99974527]
 [0.9996191 ]
 [0.99973613]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99974831]
 [0.99962341]
 [0.99973926]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99975128]
 [0.99962762]
 [0.99974233]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99993485]
 [0.99989534]
 [0.99993205]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99993506]
 [0.99989565]
 [0.99993227]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99993526]
 [0.99989596]
 [0.99993248]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99993547]
 [0.99989627]
 [0.99993269]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99993567]
 [0.99989658]
 [0.9999329 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99996564]
 [0.99994291]
 [0.99996405]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999657 ]
 [0.99994301]
 [0.99996411]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99996576]
 [0.9999431 ]
 [0.99996417]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99996582]
 [0.99994319]
 [0.99996423]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99996587]
 [0.99994328]
 [0.99996429]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99997659]
 [0.99996031]
 [0.99997546]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99997662]
 [0.99996036]
 [0.99997549]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99997665]
 [0.9999604 ]
 [0.99997552]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99997667]
 [0.99996044]
 [0.99997555]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999767 ]
 [0.99996049]
 [0.99997557]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998271]
 [0.99997022]
 [0.99998185]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998273]
 [0.99997024]
 [0.99998186]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998274]
 [0.99997027]
 [0.99998188]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998276]
 [0.99997029]
 [0.9999819 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998277]
 [0.99997032]
 [0.99998191]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998619]
 [0.99997593]
 [0.99998548]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999862 ]
 [0.99997594]
 [0.99998549]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998621]
 [0.99997596]
 [0.9999855 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998622]
 [0.99997597]
 [0.99998551]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998623]
 [0.99997599]
 [0.99998552]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998835]
 [0.99997951]
 [0.99998774]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998835]
 [0.99997952]
 [0.99998775]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998836]
 [0.99997953]
 [0.99998776]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998837]
 [0.99997954]
 [0.99998776]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998837]
 [0.99997955]
 [0.99998777]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998991]
 [0.99998212]
 [0.99998938]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998992]
 [0.99998213]
 [0.99998939]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998992]
 [0.99998214]
 [0.99998939]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998993]
 [0.99998215]
 [0.9999894 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99998993]
 [0.99998216]
 [0.9999894 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999911 ]
 [0.99998412]
 [0.99999062]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999911 ]
 [0.99998413]
 [0.99999063]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999111]
 [0.99998413]
 [0.99999063]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999111]
 [0.99998414]
 [0.99999064]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999111]
 [0.99998415]
 [0.99999064]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999207]
 [0.99998576]
 [0.99999164]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999207]
 [0.99998577]
 [0.99999164]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999207]
 [0.99998577]
 [0.99999164]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999208]
 [0.99998578]
 [0.99999165]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999208]
 [0.99998578]
 [0.99999165]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999294]
 [0.99998726]
 [0.99999256]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999295]
 [0.99998726]
 [0.99999256]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999295]
 [0.99998727]
 [0.99999256]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999295]
 [0.99998727]
 [0.99999257]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999295]
 [0.99998728]
 [0.99999257]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999353]
 [0.99998826]
 [0.99999317]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999353]
 [0.99998827]
 [0.99999317]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999353]
 [0.99998827]
 [0.99999318]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999353]
 [0.99998827]
 [0.99999318]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999354]
 [0.99998828]
 [0.99999318]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999941 ]
 [0.99998924]
 [0.99999377]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999941 ]
 [0.99998924]
 [0.99999377]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999941 ]
 [0.99998925]
 [0.99999377]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999941 ]
 [0.99998925]
 [0.99999378]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.9999941 ]
 [0.99998925]
 [0.99999378]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999447]
 [0.99998988]
 [0.99999416]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999447]
 [0.99998989]
 [0.99999416]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999447]
 [0.99998989]
 [0.99999416]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999447]
 [0.99998989]
 [0.99999416]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999447]
 [0.99998989]
 [0.99999417]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999482]
 [0.9999905 ]
 [0.99999453]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999482]
 [0.9999905 ]
 [0.99999453]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999482]
 [0.9999905 ]
 [0.99999453]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999483]
 [0.9999905 ]
 [0.99999454]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999483]
 [0.99999051]
 [0.99999454]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999515]
 [0.99999106]
 [0.99999487]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999515]
 [0.99999106]
 [0.99999487]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999515]
 [0.99999107]
 [0.99999487]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999515]
 [0.99999107]
 [0.99999488]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999515]
 [0.99999107]
 [0.99999488]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999548]
 [0.99999165]
 [0.99999523]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999548]
 [0.99999165]
 [0.99999523]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999549]
 [0.99999166]
 [0.99999523]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999549]
 [0.99999166]
 [0.99999523]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999549]
 [0.99999166]
 [0.99999523]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999577]
 [0.99999215]
 [0.99999552]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999577]
 [0.99999215]
 [0.99999553]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999577]
 [0.99999215]
 [0.99999553]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999577]
 [0.99999215]
 [0.99999553]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999577]
 [0.99999215]
 [0.99999553]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999604]
 [0.99999263]
 [0.99999581]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999604]
 [0.99999263]
 [0.99999581]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999604]
 [0.99999263]
 [0.99999581]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999604]
 [0.99999263]
 [0.99999581]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999604]
 [0.99999263]
 [0.99999581]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999628]
 [0.99999305]
 [0.99999606]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999628]
 [0.99999305]
 [0.99999606]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999628]
 [0.99999305]
 [0.99999606]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999628]
 [0.99999305]
 [0.99999606]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999628]
 [0.99999305]
 [0.99999606]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999649]
 [0.99999343]
 [0.99999629]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999649]
 [0.99999343]
 [0.99999629]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999649]
 [0.99999343]
 [0.99999629]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999649]
 [0.99999343]
 [0.99999629]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999649]
 [0.99999343]
 [0.99999629]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999666]
 [0.99999373]
 [0.99999646]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999666]
 [0.99999373]
 [0.99999646]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999666]
 [0.99999373]
 [0.99999646]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999666]
 [0.99999373]
 [0.99999647]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999666]
 [0.99999373]
 [0.99999647]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999683]
 [0.99999404]
 [0.99999665]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999683]
 [0.99999404]
 [0.99999665]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999683]
 [0.99999404]
 [0.99999665]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999684]
 [0.99999404]
 [0.99999665]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999684]
 [0.99999404]
 [0.99999665]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999695]
 [0.99999424]
 [0.99999677]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999695]
 [0.99999424]
 [0.99999677]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999695]
 [0.99999424]
 [0.99999677]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999695]
 [0.99999424]
 [0.99999677]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999695]
 [0.99999424]
 [0.99999677]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999707]
 [0.99999446]
 [0.9999969 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999707]
 [0.99999446]
 [0.9999969 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999707]
 [0.99999446]
 [0.9999969 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999707]
 [0.99999446]
 [0.9999969 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999707]
 [0.99999446]
 [0.9999969 ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/

Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999717]
 [0.99999464]
 [0.999997  ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999717]
 [0.99999464]
 [0.999997  ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999717]
 [0.99999464]
 [0.999997  ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999717]
 [0.99999464]
 [0.999997  ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/p : 
 [[92]
 [86]
 [89]]
Predicted o/p : 
 [[0.99999717]
 [0.99999464]
 [0.999997  ]]
Input : 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual o/